{"name": "test_two", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 0\n  +1\n  -0", "trace": "self = <Python_Pytest.com.kxj.case.test_02_simple.TestClassDemo object at 0x0000018A104A3438>\n\n    def test_two(self):\n>       assert 1 == 0\nE       assert 1 == 0\nE         +1\nE         -0\n\nPython_Pytest\\com\\kxj\\case\\test_02_simple.py:14: AssertionError"}, "start": 1617330625639, "stop": 1617330625639, "uuid": "34e91b24-8fe8-4fdb-8ae5-5baa53021fce", "historyId": "53706487664e6318e85468ed6d29eca2", "testCaseId": "ba638e0b99743a0dfb43bbc3f6c43009", "fullName": "com.kxj.case.test_02_simple.TestClassDemo#test_two", "labels": [{"name": "parentSuite", "value": "com.kxj.case"}, {"name": "suite", "value": "test_02_simple"}, {"name": "subSuite", "value": "TestClassDemo"}, {"name": "host", "value": "DESKTOP-4IJL66C"}, {"name": "thread", "value": "3396-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "com.kxj.case.test_02_simple"}]}